import "~/styles/globals.css";
import "@uploadthing/react/styles.css";


import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import TopNav from "./_components/topnav";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "T3 Gallery",
  description: "Generated by a loyal dev",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});


export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
    <body className={`font-sans ${geist.variable}`}>
      <ClerkProvider>
        <TopNav />
        {children}
      </ClerkProvider>
    </body>
    </html>
  );
}
